"""Fleet Telemetry Docker Compose stack orchestration.

Manages the lifecycle of a self-hosted Tesla fleet-telemetry server:
TLS certificate generation and the fleet-telemetry Go server container.

No third-party services required — vehicles stream directly to your server.
"""

from __future__ import annotations

import copy
import json
import socket
import subprocess
import time
from pathlib import Path
from typing import Any

from tesla_cli.core.config import CONFIG_DIR
from tesla_cli.core.exceptions import DockerNotFoundError, TeslaMateStackError

DEFAULT_STACK_DIR = CONFIG_DIR / "fleet-telemetry"

# ---------------------------------------------------------------------------
# Docker Compose template
# ---------------------------------------------------------------------------

COMPOSE_TEMPLATE = """\
# Auto-generated by tesla-cli — do not edit manually.
# Managed fleet-telemetry stack: Tesla fleet-telemetry Go server

services:
  fleet-telemetry:
    image: tesla/fleet-telemetry:latest
    ports:
      - "${FT_PORT:-4443}:${FT_PORT:-4443}"
    volumes:
      - ./config.json:/etc/fleet-telemetry/config.json
      - ./certs:/etc/fleet-telemetry/certs
    command: ["-config", "/etc/fleet-telemetry/config.json"]
    restart: unless-stopped
"""

COMPOSE_TEMPLATE_WITH_TESLAMATE_NETWORK = """\
# Auto-generated by tesla-cli — do not edit manually.
# Managed fleet-telemetry stack: Tesla fleet-telemetry Go server
# Joined to TeslaMate network for direct Mosquitto access.

services:
  fleet-telemetry:
    image: tesla/fleet-telemetry:latest
    ports:
      - "${FT_PORT:-4443}:${FT_PORT:-4443}"
    volumes:
      - ./config.json:/etc/fleet-telemetry/config.json
      - ./certs:/etc/fleet-telemetry/certs
    command: ["-config", "/etc/fleet-telemetry/config.json"]
    restart: unless-stopped
    networks:
      - default
      - teslamate_default

networks:
  teslamate_default:
    external: true
"""

# ---------------------------------------------------------------------------
# fleet-telemetry config.json template
# ---------------------------------------------------------------------------

CONFIG_TEMPLATE = {
    "host": "0.0.0.0",
    "port": 4443,
    "log_level": "info",
    "tls": {
        "server_cert": "/etc/fleet-telemetry/certs/server.crt",
        "server_key": "/etc/fleet-telemetry/certs/server.key",
    },
    "records": {
        "alerts": ["logger", "mqtt"],
        "errors": ["logger"],
        "V": ["logger", "mqtt"],
    },
    "logger": {
        "verbose": True,
    },
    "mqtt": {
        "host": "localhost",
        "port": 1883,
        "topic": "tesla/telemetry/{vin}",
    },
}


class FleetTelemetryStackError(TeslaMateStackError):
    """Error managing the fleet-telemetry Docker stack."""


class FleetTelemetryStack:
    """Orchestrates the fleet-telemetry Docker Compose stack."""

    def __init__(self, stack_dir: Path | None = None) -> None:
        self.stack_dir = Path(stack_dir) if stack_dir else DEFAULT_STACK_DIR
        self.compose_file = self.stack_dir / "docker-compose.yml"
        self.config_file = self.stack_dir / "config.json"
        self.certs_dir = self.stack_dir / "certs"
        self.env_file = self.stack_dir / ".env"

    # ------------------------------------------------------------------
    # Pre-flight checks
    # ------------------------------------------------------------------

    @staticmethod
    def check_docker() -> None:
        """Verify Docker daemon is reachable."""
        try:
            r = subprocess.run(
                ["docker", "info"],
                capture_output=True,
                timeout=15,
            )
            if r.returncode != 0:
                raise DockerNotFoundError(
                    "Docker is installed but the daemon is not running.\n"
                    "Start Docker Desktop or run: sudo systemctl start docker"
                )
        except FileNotFoundError:
            raise DockerNotFoundError(
                "Install Docker: https://docs.docker.com/get-docker/\n"
                "  macOS: brew install --cask docker\n"
                "  Linux: curl -fsSL https://get.docker.com | sh"
            )

    @staticmethod
    def check_docker_compose() -> str:
        """Verify docker compose v2 is available. Returns version string."""
        try:
            r = subprocess.run(
                ["docker", "compose", "version", "--short"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if r.returncode != 0:
                raise DockerNotFoundError(
                    "`docker compose` plugin not found.\n"
                    "Install: https://docs.docker.com/compose/install/"
                )
            return r.stdout.strip()
        except FileNotFoundError:
            raise DockerNotFoundError("Docker not found on PATH.")

    @staticmethod
    def check_openssl() -> None:
        """Verify openssl is available for certificate generation."""
        try:
            subprocess.run(
                ["openssl", "version"],
                capture_output=True,
                timeout=5,
                check=True,
            )
        except (FileNotFoundError, subprocess.CalledProcessError):
            raise FleetTelemetryStackError(
                "openssl not found. Install it:\n"
                "  macOS: brew install openssl\n"
                "  Linux: sudo apt-get install openssl"
            )

    @staticmethod
    def port_in_use(port: int) -> bool:
        """Check if a TCP port is already bound on localhost."""
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1)
            return s.connect_ex(("127.0.0.1", port)) == 0

    # ------------------------------------------------------------------
    # Installation
    # ------------------------------------------------------------------

    def is_installed(self) -> bool:
        return self.compose_file.exists()

    def install(
        self,
        *,
        hostname: str,
        port: int = 4443,
        force: bool = False,
        teslaMate_managed: bool = False,
        mqtt_host: str = "localhost",
        mqtt_port: int = 1883,
    ) -> dict[str, Any]:
        """Provision the fleet-telemetry stack with TLS certificates.

        Generates a self-signed CA + server certificate, writes the Docker
        Compose file and config.json, then pulls and starts the container.

        When ``teslaMate_managed`` is True the fleet-telemetry container joins
        the TeslaMate Docker network so it can reach Mosquitto by its service
        name (``mosquitto``), and ``mqtt_host`` defaults to ``mosquitto``.

        Returns a dict with cert paths, port, and status for the caller
        to persist in config.toml.
        """
        if self.is_installed() and not force:
            raise FleetTelemetryStackError(
                "Fleet-telemetry stack already installed.\n"
                "Use --force to reinstall, or `tesla telemetry start` to start."
            )

        self.check_docker()
        self.check_docker_compose()
        self.check_openssl()

        if self.port_in_use(port) and not force:
            raise FleetTelemetryStackError(
                f"Port {port} is already in use.\n"
                "Choose a different port with --port or stop the conflicting service."
            )

        # Create directory structure
        self.stack_dir.mkdir(parents=True, exist_ok=True)
        self.certs_dir.mkdir(parents=True, exist_ok=True)

        # Generate TLS certificates
        ca_cert, server_cert, server_key = self._generate_certs(hostname)

        # Write Compose file — join TeslaMate network when managed together
        compose_template = (
            COMPOSE_TEMPLATE_WITH_TESLAMATE_NETWORK if teslaMate_managed else COMPOSE_TEMPLATE
        )
        self.compose_file.write_text(compose_template)

        # Resolve MQTT broker host: prefer Mosquitto container name when in same network
        resolved_mqtt_host = "mosquitto" if teslaMate_managed else mqtt_host

        # Write config.json with correct port and MQTT dispatcher
        cfg = copy.deepcopy(CONFIG_TEMPLATE)
        cfg["port"] = port
        cfg["mqtt"]["host"] = resolved_mqtt_host
        cfg["mqtt"]["port"] = mqtt_port
        self.config_file.write_text(json.dumps(cfg, indent=2) + "\n")

        # Write .env
        self.env_file.write_text(f"FT_PORT={port}\n")
        self.env_file.chmod(0o600)

        # Pull image + start
        self._docker_compose("pull")
        self._docker_compose("up", "-d")

        healthy = self._wait_healthy(timeout=60)

        return {
            "stack_dir": str(self.stack_dir),
            "hostname": hostname,
            "port": port,
            "ca_cert_path": ca_cert,
            "server_cert_path": server_cert,
            "server_key_path": server_key,
            "healthy": healthy,
            "mqtt_host": resolved_mqtt_host,
            "mqtt_port": mqtt_port,
        }

    # ------------------------------------------------------------------
    # TLS certificate generation
    # ------------------------------------------------------------------

    def _generate_certs(self, hostname: str) -> tuple[str, str, str]:
        """Generate self-signed CA + server certificate via openssl.

        Returns (ca_cert_path, server_cert_path, server_key_path).
        """
        ca_key = str(self.certs_dir / "ca.key")
        ca_cert = str(self.certs_dir / "ca.crt")
        server_key = str(self.certs_dir / "server.key")
        server_csr = str(self.certs_dir / "server.csr")
        server_cert = str(self.certs_dir / "server.crt")

        # Generate CA key + self-signed cert
        subprocess.run(
            ["openssl", "genrsa", "-out", ca_key, "4096"],
            capture_output=True, check=True, timeout=30,
        )
        subprocess.run(
            [
                "openssl", "req", "-new", "-x509", "-days", "3650",
                "-key", ca_key, "-out", ca_cert,
                "-subj", "/CN=fleet-telemetry-ca/O=tesla-cli",
            ],
            capture_output=True, check=True, timeout=30,
        )

        # Generate server key + CSR
        subprocess.run(
            ["openssl", "genrsa", "-out", server_key, "4096"],
            capture_output=True, check=True, timeout=30,
        )
        subprocess.run(
            [
                "openssl", "req", "-new",
                "-key", server_key, "-out", server_csr,
                "-subj", f"/CN={hostname}/O=tesla-cli",
            ],
            capture_output=True, check=True, timeout=30,
        )

        # Sign server cert with CA
        ext_file = self.certs_dir / "san.ext"
        ext_file.write_text(
            f"subjectAltName=DNS:{hostname},IP:127.0.0.1\n"
            "keyUsage=digitalSignature,keyEncipherment\n"
            "extendedKeyUsage=serverAuth\n"
        )
        subprocess.run(
            [
                "openssl", "x509", "-req", "-days", "3650",
                "-in", server_csr, "-CA", ca_cert, "-CAkey", ca_key,
                "-CAcreateserial", "-out", server_cert,
                "-extfile", str(ext_file),
            ],
            capture_output=True, check=True, timeout=30,
        )
        ext_file.unlink(missing_ok=True)

        # Restrict key permissions
        Path(ca_key).chmod(0o600)
        Path(server_key).chmod(0o600)

        return ca_cert, server_cert, server_key

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        self._require_installed()
        self._docker_compose("up", "-d")
        if not self._wait_healthy(timeout=30):
            raise FleetTelemetryStackError(
                "Stack started but fleet-telemetry did not become healthy.\n"
                "Check logs: tesla telemetry logs"
            )

    def stop(self) -> None:
        self._require_installed()
        self._docker_compose("stop")

    def restart(self) -> None:
        self._require_installed()
        self._docker_compose("restart")

    def logs(
        self,
        lines: int = 100,
        follow: bool = False,
    ) -> subprocess.CompletedProcess[str] | subprocess.Popen[str]:
        """Show fleet-telemetry logs. If follow=True returns a Popen for streaming."""
        self._require_installed()
        args = ["logs", f"--tail={lines}"]
        if follow:
            args.append("-f")
        args.append("fleet-telemetry")

        if follow:
            return subprocess.Popen(
                ["docker", "compose", "-f", str(self.compose_file), *args],
                cwd=self.stack_dir,
                text=True,
            )
        return self._docker_compose(*args, capture=True)

    def uninstall(self, *, remove_volumes: bool = False) -> None:
        """Stop and remove container. Optionally remove volumes."""
        self._require_installed()
        args = ["down"]
        if remove_volumes:
            args.append("-v")
        self._docker_compose(*args)

    # ------------------------------------------------------------------
    # Status & health
    # ------------------------------------------------------------------

    def status(self) -> list[dict[str, Any]]:
        """Return per-service status from docker compose ps."""
        if not self.is_installed():
            return []
        result = self._docker_compose("ps", "--format", "json", capture=True)
        if not result.stdout or not result.stdout.strip():
            return []
        services = []
        for line in result.stdout.strip().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                services.append(
                    {
                        "name": obj.get("Service", obj.get("Name", "")),
                        "state": obj.get("State", "unknown"),
                        "status": obj.get("Status", ""),
                        "image": obj.get("Image", ""),
                        "ports": obj.get("Ports", obj.get("Publishers", "")),
                    }
                )
            except json.JSONDecodeError:
                continue
        return services

    def is_running(self) -> bool:
        """Check if the fleet-telemetry container is running."""
        return any(svc.get("state") == "running" for svc in self.status())

    def health_check(self) -> dict[str, bool]:
        """Per-service running/not-running map."""
        return {svc["name"]: svc.get("state") == "running" for svc in self.status()}

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _require_installed(self) -> None:
        if not self.is_installed():
            raise FleetTelemetryStackError(
                "Fleet-telemetry stack is not installed.\nRun: tesla telemetry install"
            )

    def _docker_compose(
        self, *args: str, capture: bool = False
    ) -> subprocess.CompletedProcess[str]:
        """Run a docker compose command in the stack directory."""
        cmd = ["docker", "compose", "-f", str(self.compose_file), *args]
        return subprocess.run(
            cmd,
            cwd=self.stack_dir,
            capture_output=capture,
            text=True,
            timeout=300,
        )

    def _wait_healthy(self, timeout: int = 60) -> bool:
        """Poll until fleet-telemetry container is running, or timeout."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if self.is_running():
                return True
            time.sleep(2)
        return False
