"""TeslaMate Docker Compose stack orchestration.

Manages the full lifecycle of a local TeslaMate installation:
PostgreSQL, TeslaMate, Grafana, and Mosquitto — all via Docker Compose.
"""

from __future__ import annotations

import json
import secrets
import socket
import subprocess
import time
from pathlib import Path
from typing import Any

from tesla_cli.core.auth.tokens import (
    FLEET_ACCESS_TOKEN,
    FLEET_REFRESH_TOKEN,
    ORDER_ACCESS_TOKEN,
    ORDER_REFRESH_TOKEN,
    TESLAMATE_DB_PASSWORD,
    TESLAMATE_ENCRYPTION_KEY,
    TESLAMATE_GRAFANA_PASSWORD,
    get_token,
    has_token,
    set_token,
)
from tesla_cli.core.config import CONFIG_DIR
from tesla_cli.core.exceptions import DockerNotFoundError, TeslaMateStackError

DEFAULT_STACK_DIR = CONFIG_DIR / "teslamate"

# ---------------------------------------------------------------------------
# Docker Compose template
# ---------------------------------------------------------------------------

COMPOSE_TEMPLATE = """\
# Auto-generated by tesla-cli — do not edit manually.
# Managed TeslaMate stack: PostgreSQL + TeslaMate + Grafana + Mosquitto

services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: teslamate
      POSTGRES_PASSWORD: ${TM_DB_PASSWORD}
      POSTGRES_DB: teslamate
    ports:
      - "${TM_DB_PORT:-5432}:5432"
    volumes:
      - teslamate-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teslamate"]
      interval: 5s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "${TM_MQTT_PORT:-1883}:1883"
    volumes:
      - teslamate-mosquitto-conf:/mosquitto/config
      - teslamate-mosquitto-data:/mosquitto/data
    command: mosquitto -c /mosquitto-no-auth.conf
    entrypoint: >
      sh -c "printf 'listener 1883\\nallow_anonymous true\\n' > /mosquitto-no-auth.conf && exec mosquitto -c /mosquitto-no-auth.conf"

  teslamate:
    image: teslamate/teslamate:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_USER: teslamate
      DATABASE_PASS: ${TM_DB_PASSWORD}
      DATABASE_NAME: teslamate
      DATABASE_HOST: postgres
      MQTT_HOST: mosquitto
      ENCRYPTION_KEY: ${TM_ENCRYPTION_KEY}
      TZ: ${TM_TIMEZONE:-America/Bogota}
    ports:
      - "${TM_PORT:-4000}:4000"
    cap_drop:
      - all

  grafana:
    image: teslamate/grafana:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_USER: teslamate
      DATABASE_PASS: ${TM_DB_PASSWORD}
      DATABASE_NAME: teslamate
      DATABASE_HOST: postgres
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${TM_GRAFANA_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_SERVER_ROOT_URL: http://localhost:${TM_GRAFANA_PORT:-3000}
    ports:
      - "${TM_GRAFANA_PORT:-3000}:3000"
    volumes:
      - teslamate-grafana-data:/var/lib/grafana

volumes:
  teslamate-db:
  teslamate-grafana-data:
  teslamate-mosquitto-conf:
  teslamate-mosquitto-data:
"""


class TeslaMateStack:
    """Orchestrates the TeslaMate Docker Compose stack."""

    def __init__(self, stack_dir: Path | None = None) -> None:
        self.stack_dir = Path(stack_dir) if stack_dir else DEFAULT_STACK_DIR
        self.compose_file = self.stack_dir / "docker-compose.yml"
        self.env_file = self.stack_dir / ".env"

    # ------------------------------------------------------------------
    # Pre-flight checks
    # ------------------------------------------------------------------

    @staticmethod
    def check_docker() -> None:
        """Verify Docker daemon is reachable."""
        try:
            r = subprocess.run(
                ["docker", "info"],
                capture_output=True,
                timeout=15,
            )
            if r.returncode != 0:
                raise DockerNotFoundError(
                    "Docker is installed but the daemon is not running.\n"
                    "Start Docker Desktop or run: sudo systemctl start docker"
                )
        except FileNotFoundError:
            raise DockerNotFoundError(
                "Install Docker: https://docs.docker.com/get-docker/\n"
                "  macOS: brew install --cask docker\n"
                "  Linux: curl -fsSL https://get.docker.com | sh"
            )

    @staticmethod
    def check_docker_compose() -> str:
        """Verify docker compose v2 is available. Returns version string."""
        try:
            r = subprocess.run(
                ["docker", "compose", "version", "--short"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if r.returncode != 0:
                raise DockerNotFoundError(
                    "`docker compose` plugin not found.\n"
                    "Install: https://docs.docker.com/compose/install/"
                )
            return r.stdout.strip()
        except FileNotFoundError:
            raise DockerNotFoundError("Docker not found on PATH.")

    @staticmethod
    def port_in_use(port: int) -> bool:
        """Check if a TCP port is already bound on localhost."""
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1)
            return s.connect_ex(("127.0.0.1", port)) == 0

    def check_ports(
        self,
        postgres_port: int,
        grafana_port: int,
        teslamate_port: int,
        mqtt_port: int,
    ) -> list[tuple[str, int]]:
        """Return list of (service, port) pairs that are already in use."""
        conflicts = []
        for name, port in [
            ("PostgreSQL", postgres_port),
            ("Grafana", grafana_port),
            ("TeslaMate", teslamate_port),
            ("Mosquitto", mqtt_port),
        ]:
            if self.port_in_use(port):
                conflicts.append((name, port))
        return conflicts

    # ------------------------------------------------------------------
    # Installation
    # ------------------------------------------------------------------

    def is_installed(self) -> bool:
        return self.compose_file.exists()

    def install(
        self,
        *,
        postgres_port: int = 5432,
        grafana_port: int = 3000,
        teslamate_port: int = 4000,
        mqtt_port: int = 1883,
        timezone: str = "America/Bogota",
        force: bool = False,
    ) -> dict[str, Any]:
        """Provision the full TeslaMate stack.

        Returns a dict with credentials, ports, and status for the caller
        to persist in config.toml.
        """
        if self.is_installed() and not force:
            raise TeslaMateStackError(
                "TeslaMate stack already installed.\n"
                "Use --force to reinstall, or `tesla teslaMate start` to start."
            )

        self.check_docker()
        self.check_docker_compose()

        # Generate or reuse credentials
        db_password = get_token(TESLAMATE_DB_PASSWORD) or secrets.token_urlsafe(24)
        grafana_password = get_token(TESLAMATE_GRAFANA_PASSWORD) or secrets.token_urlsafe(16)
        encryption_key = get_token(TESLAMATE_ENCRYPTION_KEY) or secrets.token_urlsafe(32)

        set_token(TESLAMATE_DB_PASSWORD, db_password)
        set_token(TESLAMATE_GRAFANA_PASSWORD, grafana_password)
        set_token(TESLAMATE_ENCRYPTION_KEY, encryption_key)

        # Look for Tesla tokens to seed TeslaMate
        tesla_access = get_token(FLEET_ACCESS_TOKEN) or get_token(ORDER_ACCESS_TOKEN)
        tesla_refresh = get_token(FLEET_REFRESH_TOKEN) or get_token(ORDER_REFRESH_TOKEN)

        # Generate files
        self.stack_dir.mkdir(parents=True, exist_ok=True)
        self.compose_file.write_text(COMPOSE_TEMPLATE)

        env_lines = [
            f"TM_DB_PASSWORD={db_password}",
            f"TM_GRAFANA_PASSWORD={grafana_password}",
            f"TM_ENCRYPTION_KEY={encryption_key}",
            f"TM_DB_PORT={postgres_port}",
            f"TM_PORT={teslamate_port}",
            f"TM_GRAFANA_PORT={grafana_port}",
            f"TM_MQTT_PORT={mqtt_port}",
            f"TM_TIMEZONE={timezone}",
        ]
        if tesla_access:
            env_lines.append(f"TESLA_ACCESS_TOKEN={tesla_access}")
        if tesla_refresh:
            env_lines.append(f"TESLA_REFRESH_TOKEN={tesla_refresh}")

        self.env_file.write_text("\n".join(env_lines) + "\n")
        # Restrict permissions on .env (contains secrets)
        self.env_file.chmod(0o600)

        # Pull images + start
        self._docker_compose("pull")
        self._docker_compose("up", "-d")

        # Wait for healthy
        healthy = self._wait_healthy(timeout=90)

        database_url = (
            f"postgresql://teslamate:{db_password}@localhost:{postgres_port}/teslamate"
        )

        return {
            "database_url": database_url,
            "stack_dir": str(self.stack_dir),
            "postgres_port": postgres_port,
            "grafana_port": grafana_port,
            "teslamate_port": teslamate_port,
            "mqtt_port": mqtt_port,
            "healthy": healthy,
            "has_tesla_tokens": bool(tesla_access and tesla_refresh),
            "grafana_password": grafana_password,
        }

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        self._require_installed()
        self._docker_compose("up", "-d")
        if not self._wait_healthy(timeout=60):
            raise TeslaMateStackError(
                "Stack started but not all services are healthy.\n"
                "Check logs: tesla teslaMate logs"
            )

    def stop(self) -> None:
        self._require_installed()
        self._docker_compose("stop")

    def restart(self) -> None:
        self._require_installed()
        self._docker_compose("restart")
        if not self._wait_healthy(timeout=60):
            raise TeslaMateStackError(
                "Stack restarted but not all services are healthy.\n"
                "Check logs: tesla teslaMate logs"
            )

    def update(self) -> str:
        """Pull latest images and recreate containers. Returns pull output."""
        self._require_installed()
        result = self._docker_compose("pull", capture=True)
        self._docker_compose("up", "-d")
        self._wait_healthy(timeout=90)
        return result.stdout or ""

    def logs(
        self,
        service: str | None = None,
        lines: int = 100,
        follow: bool = False,
    ) -> subprocess.CompletedProcess[str] | subprocess.Popen[str]:
        """Show logs. If follow=True returns a Popen for streaming."""
        self._require_installed()
        args = ["logs", f"--tail={lines}"]
        if follow:
            args.append("-f")
        if service:
            args.append(service)

        if follow:
            return subprocess.Popen(
                ["docker", "compose", "-f", str(self.compose_file), *args],
                cwd=self.stack_dir,
                text=True,
            )
        return self._docker_compose(*args, capture=True)

    def uninstall(self, *, remove_volumes: bool = False) -> None:
        """Stop and remove containers. Optionally remove volumes."""
        self._require_installed()
        args = ["down"]
        if remove_volumes:
            args.append("-v")
        self._docker_compose(*args)

    # ------------------------------------------------------------------
    # Status & health
    # ------------------------------------------------------------------

    def status(self) -> list[dict[str, Any]]:
        """Return per-service status from docker compose ps."""
        if not self.is_installed():
            return []
        result = self._docker_compose("ps", "--format", "json", capture=True)
        if not result.stdout or not result.stdout.strip():
            return []
        # docker compose ps --format json outputs one JSON object per line
        services = []
        for line in result.stdout.strip().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                services.append({
                    "name": obj.get("Service", obj.get("Name", "")),
                    "state": obj.get("State", "unknown"),
                    "status": obj.get("Status", ""),
                    "image": obj.get("Image", ""),
                    "ports": obj.get("Ports", obj.get("Publishers", "")),
                })
            except json.JSONDecodeError:
                continue
        return services

    def is_running(self) -> bool:
        """Check if the stack has at least one running container."""
        for svc in self.status():
            if svc.get("state") == "running":
                return True
        return False

    def health_check(self) -> dict[str, bool]:
        """Per-service running/not-running map."""
        result: dict[str, bool] = {}
        for svc in self.status():
            result[svc["name"]] = svc.get("state") == "running"
        return result

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _require_installed(self) -> None:
        if not self.is_installed():
            raise TeslaMateStackError(
                "TeslaMate stack is not installed.\n"
                "Run: tesla teslaMate install"
            )

    def _docker_compose(
        self, *args: str, capture: bool = False
    ) -> subprocess.CompletedProcess[str]:
        """Run a docker compose command in the stack directory."""
        cmd = ["docker", "compose", "-f", str(self.compose_file), *args]
        return subprocess.run(
            cmd,
            cwd=self.stack_dir,
            capture_output=capture,
            text=True,
            timeout=300,
        )

    def _wait_healthy(self, timeout: int = 60) -> bool:
        """Poll until all 4 services are running, or timeout."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            health = self.health_check()
            if len(health) >= 4 and all(health.values()):
                return True
            time.sleep(3)
        return False
